version: '3.8'

services:
  #  app:
  #    image: resource_usage_app_pg:latest
  #    restart: always
  #    ports:
  #      - "10700:10700"
  #    env_file: .env
  #    environment:
  #      - DB_USERNAME=$DB_USERNAME
  #      - DB_PASSWORD=$DB_PASSWORD
  #      - DB_HOSTNAME=db
  #      - DB_NAME=$DB_NAME
  #      - DB_PORT=$DB_PORT
  #    depends_on:
  #      db:
  #        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - resource-usage-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  resource-usage-postgres-data: