version: '3.8'

services:
  app:
    image: resource_usage_app:latest
    entrypoint: ./entrypoint.sh
    restart: always
    ports:
      - "31210:5000"
    env_file: .env
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOSTNAME=db
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.29
    restart: always
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    volumes:
      - resource_app_db_data:/var/lib/mysql
volumes:
  resource_app_db_data: